// 意大利语动词词库（后端 ES module）
// 来源：前端 js/verbs.js，保持完全一致

const VERBS = [
  // ========== 不规则动词 ==========
  { i:"essere",     t:"irregular", a:"essere",  pp:"stato",
    pr:["sono","sei","è","siamo","siete","sono"],
    imf:["ero","eri","era","eravamo","eravate","erano"],
    imp:["sii","sia","siamo","siate","siano"] },
  { i:"avere",      t:"irregular", a:"avere",  pp:"avuto",
    pr:["ho","hai","ha","abbiamo","avete","hanno"],
    imp:["abbi","abbia","abbiamo","abbiate","abbiano"] },
  { i:"andare",     t:"irregular", a:"essere",  pp:"andato",
    pr:["vado","vai","va","andiamo","andate","vanno"],
    imp:["va'","vada","andiamo","andate","vadano"] },
  { i:"dare",       t:"irregular", a:"avere",  pp:"dato",
    pr:["do","dai","dà","diamo","date","danno"],
    imp:["da'","dia","diamo","diate","diano"] },
  { i:"stare",      t:"irregular", a:"essere",  pp:"stato",
    pr:["sto","stai","sta","stiamo","state","stanno"],
    imp:["sta'","stia","stiamo","stiate","stiano"] },
  { i:"fare",       t:"irregular", a:"avere",  pp:"fatto",
    pr:["faccio","fai","fa","facciamo","fate","fanno"],
    imf:["facevo","facevi","faceva","facevamo","facevate","facevano"],
    imp:["fa'","faccia","facciamo","fate","facciano"] },
  { i:"dire",       t:"irregular", a:"avere",  pp:"detto",
    pr:["dico","dici","dice","diciamo","dite","dicono"],
    imf:["dicevo","dicevi","diceva","dicevamo","dicevate","dicevano"],
    imp:["di'","dica","diciamo","dite","dicano"] },
  { i:"bere",       t:"irregular", a:"avere",  pp:"bevuto",
    pr:["bevo","bevi","beve","beviamo","bevete","bevono"],
    imf:["bevevo","bevevi","beveva","bevevamo","bevevate","bevevano"] },
  { i:"sapere",     t:"irregular", a:"avere",  pp:"saputo",
    pr:["so","sai","sa","sappiamo","sapete","sanno"],
    imp:["sappi","sappia","sappiamo","sappiate","sappiano"] },
  { i:"volere",     t:"irregular", a:"avere",  pp:"voluto",
    pr:["voglio","vuoi","vuole","vogliamo","volete","vogliono"] },
  { i:"dovere",     t:"irregular", a:"avere",  pp:"dovuto",
    pr:["devo","devi","deve","dobbiamo","dovete","devono"] },
  { i:"potere",     t:"irregular", a:"avere",  pp:"potuto",
    pr:["posso","puoi","può","possiamo","potete","possono"] },
  { i:"venire",     t:"irregular", a:"essere",  pp:"venuto",
    pr:["vengo","vieni","viene","veniamo","venite","vengono"],
    imp:["vieni","venga","veniamo","venite","vengano"] },
  { i:"morire",     t:"irregular", a:"essere",  pp:"morto",
    pr:["muoio","muori","muore","moriamo","morite","muoiono"],
    imp:["muori","muoia","moriamo","morite","muoiano"] },
  { i:"tradurre",   t:"irregular", a:"avere",  pp:"tradotto",
    pr:["traduco","traduci","traduce","traduciamo","traducete","traducono"],
    imf:["traducevo","traducevi","traduceva","traducevamo","traducevate","traducevano"],
    imp:["traduci","traduca","traduciamo","traducete","traducano"] },
  { i:"rimanere",   t:"irregular", a:"essere",  pp:"rimasto",
    pr:["rimango","rimani","rimane","rimaniamo","rimanete","rimangono"],
    imp:["rimani","rimanga","rimaniamo","rimanete","rimangano"] },
  { i:"spegnere",   t:"irregular", a:"avere",  pp:"spento",
    pr:["spengo","spegni","spegne","spegniamo","spegnete","spengono"],
    imp:["spegni","spenga","spegniamo","spegnete","spengano"] },
  { i:"cuocere",    t:"irregular", a:"avere",  pp:"cotto",
    pr:["cuocio","cuoci","cuoce","cuociamo","cuocete","cuociono"],
    imp:["cuoci","cuocia","cuociamo","cuocete","cuociano"] },
  { i:"porre",      t:"irregular", a:"avere",  pp:"posto",
    pr:["pongo","poni","pone","poniamo","ponete","pongono"],
    imp:["poni","ponga","poniamo","ponete","pongano"] },
  { i:"comporre",   t:"irregular", a:"avere",  pp:"composto",
    pr:["compongo","componi","compone","componiamo","componete","compongono"],
    imp:["componi","componga","componiamo","componete","compongano"] },
  { i:"proporre",   t:"irregular", a:"avere",  pp:"proposto",
    pr:["propongo","proponi","propone","proponiamo","proponete","propongono"],
    imp:["proponi","proponga","proponiamo","proponete","propongano"] },
  { i:"disporre",   t:"irregular", a:"avere",  pp:"disposto",
    pr:["dispongo","disponi","dispone","disponiamo","disponete","dispongono"],
    imp:["disponi","disponga","disponiamo","disponete","dispongano"] },
  { i:"salire",     t:"irregular", a:"essere",  pp:"salito",
    pr:["salgo","sali","sale","saliamo","salite","salgono"],
    imp:["sali","salga","saliamo","salite","salgano"] },
  { i:"uscire",     t:"irregular", a:"essere",  pp:"uscito",
    pr:["esco","esci","esce","usciamo","uscite","escono"],
    imp:["esci","esca","usciamo","uscite","escano"] },
  { i:"scegliere",  t:"irregular", a:"avere",  pp:"scelto",
    pr:["scelgo","scegli","sceglie","scegliamo","scegliete","scelgono"],
    imp:["scegli","scelga","scegliamo","scegliete","scelgano"] },
  { i:"togliere",   t:"irregular", a:"avere",  pp:"tolto",
    pr:["tolgo","togli","toglie","togliamo","togliete","tolgono"],
    imp:["togli","tolga","togliamo","togliete","tolgano"] },

  // --- 过去分词不规则的 -ere 动词 ---
  { i:"leggere",    t:"ere",  a:"avere",  pp:"letto" },
  { i:"correggere", t:"ere",  a:"avere",  pp:"corretto" },
  { i:"scrivere",   t:"ere",  a:"avere",  pp:"scritto" },
  { i:"friggere",   t:"ere",  a:"avere",  pp:"fritto" },
  { i:"rompere",    t:"ere",  a:"avere",  pp:"rotto" },
  { i:"piangere",   t:"ere",  a:"avere",  pp:"pianto" },
  { i:"spingere",   t:"ere",  a:"avere",  pp:"spinto" },
  { i:"vincere",    t:"ere",  a:"avere",  pp:"vinto" },
  { i:"aggiungere",  t:"ere",  a:"avere",  pp:"aggiunto" },
  { i:"dipingere",  t:"ere",  a:"avere",  pp:"dipinto" },
  { i:"assumere",   t:"ere",  a:"avere",  pp:"assunto" },
  { i:"prendere",   t:"ere",  a:"avere",  pp:"preso" },
  { i:"rendere",    t:"ere",  a:"avere",  pp:"reso" },
  { i:"accendere",  t:"ere",  a:"avere",  pp:"acceso" },
  { i:"spendere",   t:"ere",  a:"avere",  pp:"speso" },
  { i:"scendere",   t:"ere",  a:"essere",  pp:"sceso" },
  { i:"offendere",  t:"ere",  a:"avere",  pp:"offeso" },
  { i:"decidere",   t:"ere",  a:"avere",  pp:"deciso" },
  { i:"uccidere",   t:"ere",  a:"avere",  pp:"ucciso" },
  { i:"ridere",     t:"ere",  a:"avere",  pp:"riso" },
  { i:"dividere",   t:"ere",  a:"avere",  pp:"diviso" },
  { i:"chiudere",   t:"ere",  a:"avere",  pp:"chiuso" },
  { i:"concludere", t:"ere",  a:"avere",  pp:"concluso" },
  { i:"diffondere", t:"ere",  a:"avere",  pp:"diffuso" },
  { i:"chiedere",   t:"ere",  a:"avere",  pp:"chiesto" },
  { i:"rispondere", t:"ere",  a:"avere",  pp:"risposto" },
  { i:"vedere",     t:"ere",  a:"avere",  pp:"visto" },
  { i:"perdere",    t:"ere",  a:"avere",  pp:"perso" },
  { i:"correre",    t:"ere",  a:"avere",  pp:"corso" },
  { i:"mettere",    t:"ere",  a:"avere",  pp:"messo" },
  { i:"succedere",  t:"ere",  a:"essere",  pp:"successo" },
  { i:"permettere",  t:"ere",  a:"avere",  pp:"permesso" },
  { i:"esprimere",  t:"ere",  a:"avere",  pp:"espresso" },
  { i:"muovere",    t:"ere",  a:"avere",  pp:"mosso" },
  { i:"discutere",  t:"ere",  a:"avere",  pp:"discusso" },
  { i:"vivere",     t:"ere",  a:"avere",  pp:"vissuto" },
  { i:"nascere",    t:"ere",  a:"essere",  pp:"nato" },
  { i:"conoscere",  t:"ere",  a:"avere",  pp:"conosciuto" },
  { i:"crescere",   t:"ere",  a:"essere",  pp:"cresciuto" },
  { i:"piovere",    t:"ere",  a:"essere",  pp:"piovuto", note:"solo 3a pers" },

  // --- 过去分词不规则的 -ire 动词 ---
  { i:"aprire",     t:"ire",  a:"avere",  pp:"aperto" },
  { i:"offrire",    t:"ire",  a:"avere",  pp:"offerto" },
  { i:"soffrire",   t:"ire",  a:"avere",  pp:"sofferto" },
  { i:"coprire",    t:"ire",  a:"avere",  pp:"coperto" },
  { i:"scoprire",   t:"ire",  a:"avere",  pp:"scoperto" },

  // --- 自反动词 ---
  { i:"accorgersi", t:"ire",  a:"essere",  pp:"accorto", reflexive:true,
    pr:["mi accorgo","ti accorgi","si accorge","ci accorgiamo","vi accorgete","si accorgono"] },

  // --- 规则自反动词 ---
  { i:"alzarsi",     t:"are",  a:"essere",  pp:"alzato",   reflexive:true },
  { i:"lavarsi",     t:"are",  a:"essere",  pp:"lavato",   reflexive:true },
  { i:"chiamarsi",   t:"are",  a:"essere",  pp:"chiamato", reflexive:true },
  { i:"fermarsi",    t:"are",  a:"essere",  pp:"fermato",  reflexive:true },
  { i:"prepararsi",  t:"are",  a:"essere",  pp:"preparato",reflexive:true },
  { i:"rilassarsi",  t:"are",  a:"essere",  pp:"rilassato",reflexive:true },
  { i:"annoiarsi",   t:"are",  a:"essere",  pp:"annoiato", reflexive:true },
  { i:"allenarsi",   t:"are",  a:"essere",  pp:"allenato", reflexive:true },

  // ========== 规则动词 ==========
  { i:"parlare",    t:"are",  a:"avere",  pp:"parlato" },
  { i:"mangiare",   t:"are",  a:"avere",  pp:"mangiato" },
  { i:"studiare",   t:"are",  a:"avere",  pp:"studiato" },
  { i:"lavorare",   t:"are",  a:"avere",  pp:"lavorato" },
  { i:"comprare",   t:"are",  a:"avere",  pp:"comprato" },
  { i:"abitare",    t:"are",  a:"avere",  pp:"abitato" },
  { i:"cantare",    t:"are",  a:"avere",  pp:"cantato" },
  { i:"ballare",    t:"are",  a:"avere",  pp:"ballato" },
  { i:"giocare",    t:"are",  a:"avere",  pp:"giocato" },
  { i:"pagare",     t:"are",  a:"avere",  pp:"pagato" },
  { i:"spiegare",   t:"are",  a:"avere",  pp:"spiegato" },
  { i:"aspettare",  t:"are",  a:"avere",  pp:"aspettato" },
  { i:"incontrare", t:"are",  a:"avere",  pp:"incontrato" },
  { i:"pensare",    t:"are",  a:"avere",  pp:"pensato" },
  { i:"trovare",    t:"are",  a:"avere",  pp:"trovato" },
  { i:"cercare",    t:"are",  a:"avere",  pp:"cercato" },
  { i:"imparare",   t:"are",  a:"avere",  pp:"imparato" },
  { i:"insegnare",  t:"are",  a:"avere",  pp:"insegnato" },
  { i:"lasciare",   t:"are",  a:"avere",  pp:"lasciato" },
  { i:"sognare",    t:"are",  a:"avere",  pp:"sognato" },
  { i:"desiderare", t:"are",  a:"avere",  pp:"desiderato" },
  { i:"preparare",  t:"are",  a:"avere",  pp:"preparato" },
  { i:"guidare",    t:"are",  a:"avere",  pp:"guidato" },
  { i:"ordinare",   t:"are",  a:"avere",  pp:"ordinato" },
  { i:"cucinare",   t:"are",  a:"avere",  pp:"cucinato" },
  { i:"cominciare", t:"are",  a:"avere",  pp:"cominciato" },
  { i:"dimenticare",t:"are",  a:"avere",  pp:"dimenticato" },
  { i:"viaggiare",  t:"are",  a:"avere",  pp:"viaggiato" },

  { i:"credere",    t:"ere",  a:"avere",  pp:"creduto" },
  { i:"ricevere",   t:"ere",  a:"avere",  pp:"ricevuto" },
  { i:"ripetere",   t:"ere",  a:"avere",  pp:"ripetuto" },
  { i:"vendere",    t:"ere",  a:"avere",  pp:"venduto" },
  { i:"battere",    t:"ere",  a:"avere",  pp:"battuto" },
  { i:"temere",     t:"ere",  a:"avere",  pp:"temuto" },
  { i:"godere",     t:"ere",  a:"avere",  pp:"goduto" },
  { i:"dipendere",  t:"ere",  a:"avere",  pp:"dipeso" },
  { i:"assistere",  t:"ere",  a:"avere",  pp:"assistito" },
  { i:"resistere",  t:"ere",  a:"avere",  pp:"resistito" },
  { i:"possedere",  t:"ere",  a:"avere",  pp:"posseduto" },
  { i:"cadere",     t:"ere",  a:"essere",  pp:"caduto" },

  { i:"dormire",    t:"ire",  a:"avere",  pp:"dormito" },
  { i:"partire",    t:"ire",  a:"essere",  pp:"partito" },
  { i:"sentire",    t:"ire",  a:"avere",  pp:"sentito" },
  { i:"seguire",    t:"ire",  a:"avere",  pp:"seguito" },
  { i:"servire",    t:"ire",  a:"avere",  pp:"servito" },
  { i:"vestire",    t:"ire",  a:"avere",  pp:"vestito" },
  { i:"divertire",  t:"ire",  a:"avere",  pp:"divertito" },
  { i:"bollire",    t:"ire",  a:"avere",  pp:"bollito" },
  { i:"cucire",     t:"ire",  a:"avere",  pp:"cucito" },
  { i:"finire",     t:"ire-isc", a:"avere",  pp:"finito" },
  { i:"capire",     t:"ire-isc", a:"avere",  pp:"capito" },
  { i:"pulire",     t:"ire-isc", a:"avere",  pp:"pulito" },
  { i:"preferire",  t:"ire-isc", a:"avere",  pp:"preferito" },
  { i:"spedire",    t:"ire-isc", a:"avere",  pp:"spedito" },
  { i:"costruire",  t:"ire-isc", a:"avere",  pp:"costruito" },
  { i:"fornire",    t:"ire-isc", a:"avere",  pp:"fornito" },
  { i:"suggerire",  t:"ire-isc", a:"avere",  pp:"suggerito" },
  { i:"colpire",    t:"ire-isc", a:"avere",  pp:"colpito" },
];

function findVerb(infinitive) {
  return VERBS.find(v => v.i === infinitive);
}

export { VERBS, findVerb };
